version: '3.12.0'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Modifier le port si nécessaire
    environment:
      - FLASK_ENV=development  # If using Flask
    command: python app.py  # Adjust the command if necessary

# Uncomment the following section if you need a database service
# db:
#   image: postgres:latest
#   environment:
#     POSTGRES_DB: your_db_name
#     POSTGRES_USER: your_user
#     POSTGRES_PASSWORD: your_password
#   volumes:
#     - db_data:/var/lib/postgresql/data

# volumes:
#   db_data: